mybatis:
  type-aliases-package: com.qfedu.index.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shop_17?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 654321
    driver-class-name: com.mysql.cj.jdbc.Driver